server:
  port: 8010
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/ 
      suffix: .jsp
  datasource:
    # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/ds?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ''